version: 0.19.0
formatter: markdown table

recursive:
  enabled: false
  include-main: false

settings:
  lockfile: false

output:
  file: README.md
  mode: inject
  template: |-
    <!-- BEGINNING OF PRE-COMMIT-TERRAFORM DOCS HOOK -->
    {{ .Content }}
    <!-- END OF PRE-COMMIT-TERRAFORM DOCS HOOK -->
